---
spring:
  profiles: localtest


global:
  env:
    label: localtest
  domain:
    gov: ${local_domain_user:http://127.0.0.1:8005}
    internet: ${local_domain_user:http://127.0.0.1:8015}
    legal: ${local_domain_user:http://127.0.0.1:8025}
    personal: ${local_domain_user:http://127.0.0.1:8035}
    legalUaa: ${local_domain_uaa:http://127.0.0.1:8025}
    legalUaaPrivate: ${local_domain_uaa_private:http://127.0.0.1:8025}
    personalUaa: ${local_domain_uaa:http://127.0.0.1:8035}
    personalUaaPrivate: ${local_domain_uaa_private:http://127.0.0.1:8035}
    personalDefaultPage: ${local_domain_default_login_path:http://127.0.0.1:8035}   #开发演示环境为用户中心，正式环境为政务门户
    adminUaa: ${local_domain_uaa:http://127.0.0.1:8015}
    adminUaaPrivate: ${local_domain_uaa_private:http://127.0.0.1:8015}
    legalUser: ${local_domain_user:http://127.0.0.1:8025}
    legalUserPrivate: ${local_domain_user_private:http://127.0.0.1:8025}
    legalDefaultPage: ${local_domain_default_login_path:http://127.0.0.1:8025}  #开发演示环境为用户中心，正式环境为政务门户
    personalUser: ${local_domain_user:http://127.0.0.1:8035}
    personalUserPrivate: ${local_domain_user_private:http://127.0.0.1:8035}
    adminUser: ${local_domain_user:http://127.0.0.1:8015}
    adminUserPrivate: ${local_domain_user_private:http://127.0.0.1:8015}
  common:
    enableVerifyImageCode: false
  redis:
    host: ${local_redis_host:127.0.0.1:6379}
    ip: ${local_redis_ip:127.0.0.1}
    port: ${local_redis_port:6379}
  elasticsearch:
    host: ${local_es_host:192.168.103.194:9200}
    ip: ${local_es_ip:192.168.103.194}
    port: ${local_es_port:9200}
    transport: 9300
  web:
    cookie:
      domain: ${local.cookie.domain:127.0.0.1}
      adminDomain: 127.0.0.1
    govUser:
      port: ${server-port:8005}
      rootPath: ${vision-root-path:D:\user_center\webpage\admin\public}
    adminUser:
      port: ${server-port:8015}
      rootPath: ${vision-root-path:D:\user_center\webpage\admin\public}
    legalUser:
      port: ${server-port:8025}
      rootPath: ${vision-root-path:D:\user_center\webpage\legal\public}
    personalUser:
      port: ${server-port:8035}
      rootPath: ${vision-root-path:D:\user_center\webpage\personal\public}
    govUaa:
       port: ${server-port:8005}
       rootPath: ${vision-root-path:D:\user_center\webpage\admin\public}
    adminUaa:
      port: ${server-port:8015}
      rootPath: ${vision-root-path:D:\user_center\webpage\admin\public}
    legalUaa:
      port: ${server-port:8025}
      rootPath: ${vision-root-path:D:\user_center\webpage\legal\public}
    personalUaa:
      port: ${server-port:8035}
      rootPath: ${vision-root-path:D:\user_center\webpage\personal\public}

  dubbo:
    registry: zookeeper://127.0.0.1:2181
  idc:
    db:
      host: ${local.dc.db.host:192.168.103.105}
      port: ${local.dc.db.port:3306}
      name: ${local.dc.db.name:idc}
      user: ${local.dc.db.user:root}
      pass: ${local.dc.db.pass:123456}
  tdc:
    db:
      host: ${local.dc.db.host:192.168.103.105}
      port: ${local.dc.db.port:3306}
      name: ${local.dc.db.name:tdc}
      user: ${local.dc.db.user:root}
      pass: ${local.dc.db.pass:123456}
  dc:
    db:
      host: ${local.dc.db.host:192.168.103.105}
      port: ${local.dc.db.port:3306}
      name: ${local.dc.db.name:dc}
      user: ${local.dc.db.user:root}
      pass: ${local.dc.db.pass:123456}
    users:
      vendor: oss
      oss:
        writer:
          rolearn: ${local.dc.users.writer.rolearn:acs:ram::1613167192329778:role/iospreadwrite}
          key: ${local.dc.users.writer.key:LTAIJ8FK1pxYKRdp}
          secret: ${local.dc.users.writer.secret:kPuMu1n9SVumN8YoqLypLF7DUATOIZ}
          bucket: ${local.dc.users.writer.bucket:cma-it}
          endPoint: http://oss-cn-hangzhou.aliyuncs.com
        reader:
          key: ${local.dc.users.reader.key:LTAIJ8FK1pxYKRdp}
          secret: ${local.dc.users.reader.secret:kPuMu1n9SVumN8YoqLypLF7DUATOIZ}
          bucket: ${local.dc.users.reader.bucket:cma-it}
          endPoint: http://oss-cn-hangzhou.aliyuncs.com
      custom:
        storePath: "C:\\code-eg\\uploadFile\\"
        downloadPath: "C:\\code-eg\\uploadFile\\"
  mc:
    db:
      ip: "${local.mc.ip:192.168.103.105}"
      dbname: "${local.mc.db.name:epsilon-mc}"
      username: "${local.mc.db.username:root}"
      password: "${local.mc.db.password:123456}"
    sms:
      dayu:
        appKey: ${local.mc.sms.dayu.appKey:23475584}
        appSecret: ${local.mc.sms.dayu.appSecret:29bfb4cffdcd0f5f57591fa72b0deefc}
      aliyun:
        appKey: ${local.mc.sms.dayu.appKey:LTAIa1X4ZHtfbeeD}
        appSecret: ${local.mc.sms.dayu.appSecret:uLW2la2Uz4ONiugmI1BeRIljow3tOk}
      yixingtong:
        userName: zj_jlkg
        password: cma2016
        enterpriseNum: 236897
      gaoxin:
        generalAccount: lynkco
        generalPassword: lynkco123456
        marketingAccount: lynkcoyx
        marketingPassword: lynkcoyx123456
        foreignAccount: 900050
        foreignPassword: jlqc123456
        extCode: 1962
    email:
      direct:
        accessKeyId: ${local.mc.email.direct.accessKeyId:LTAIXBQ2hOqqr08v}
        secret: ${local.mc.email.direct.secret:OXTYE8JwG67vtBufHKFqwTmTaWXOXJ}
        accountName: ${local.mc.email.direct.accountName:wangqi@notice.wangqi123.top}
        fromAlias: ${local.mc.email.direct.fromAlias:iosp_admin}
    # TODO: add proper configuration
    message:
      ftl-prefix: ${local.mc.message.ftl-prefix:http://eg-user.oss-cn-shanghai.aliyuncs.com/template/email}
      message-config: ${local.mc.message.message-config:http://eg-user.oss-cn-shanghai.aliyuncs.com/template/sms/config.yaml}
  user:
    appSource: "internal"
    port: ${server-port:7780}
    db:
      ip: "${local.user.ip:127.0.0.1}"
      dbname: "${local.user.db.name:flexi_user_center}"
      username: "${local.user.db.username:root}"
      password: "${local.user.db.password:root}"
  proxy:
    proxySource: stub                                              #stub打桩 formal#正式实现
gamma:
  description: "This is localtest profiles."
ali-ons:
  access-key: "LTAIIe6cbzD2eXjs"
  secret-key: "gMYNAp55IDXYUsNzGWMBv9xCAEE8MF"
  producer-id: "PID-dop-localtest-public-test"
  consumer-id: "CID-dop-localtest-public-test"
  mc-mq-properties:
    topic-id: "dop-mc-eg-localtest-public-topic"
    consumer-id: "CID-mc-eg-localtest-public"
  backlog-mq-properties:
    topic-id: "dop-backlog-eg-localtest-public-topic"
    consumer-id: "CID-backlog-eg-localtest-public"
rocketmq:
  producer-group: "P-mc-eg-localtest-public"
  consumer-group: "C-mc-eg-localtest-public"
  instance-name: "In-mc-eg-localtest-public"
  cthread-number: 24
  name-server-address: 192.168.103.105:9876
  vip-channel-enabled: false
